# Generated by Django 4.2.4 on 2023-08-08 00:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hosting_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostinguser',
            name='number_of_miners',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
