# Generated by Django 4.2.4 on 2023-08-07 22:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hosting_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Miner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=40)),
                ('model', models.CharField(max_length=20)),
                ('mining_power', models.CharField(max_length=20)),
                ('serialInSlot6', models.CharField(max_length=250)),
                ('serialInSlot7', models.CharField(max_length=250)),
                ('serialInSlot8', models.CharField(max_length=250)),
                ('serialPSU', models.CharField(max_length=250)),
                ('maintance_mode', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosting_users.hostinguser')),
            ],
        ),
    ]
