# Generated by Django 4.2.4 on 2023-08-07 23:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_miner_name_of_miner_miner_pool_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miner',
            name='name_of_miner',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
